version: '3'

services:
  boost_python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: $http_proxy
        https_proxy: $https_proxy
    container_name: boost_python
    volumes:
    - ./:/boost_python
    working_dir: /boost_python
    tty: true

